name: Bug report 🐞
description: File a bug report
title: "[Bug]:🐞"
labels: bug
body:
  - type: checkboxes
    id: existing-issue
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened and Write Steps to Produce(ie. How u got the bug)?
      description: A concise description of what you are experiencing.
      placeholder: Tell us what you see and Write Steps to Produce: !
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add ScreenShots
      description: Add sufficient ScreenShots to explain your issue.
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: checkboxes
    id: terms
    attributes:
      label: Record
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true
        - label: "I want to work on this issue"
          required: False
        - label: "I'm willing to provide further clarification or assistance if needed."
          required: False
